default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

clickhouse: &clickhouse
  adapter: clickhouse
  url: <%= ENV.fetch("CLICKHOUSE_URL") { "http://localhost:8123" } %>
  database: fukan
  database_tasks: false

development:
  primary:
    <<: *default
    database: fukan_development
  clickhouse:
    <<: *clickhouse

test:
  primary:
    <<: *default
    database: fukan_test
  clickhouse:
    <<: *clickhouse

production:
  primary:
    <<: *default
    database: fukan_production
    username: fukan
    password: <%= ENV["FUKAN_DATABASE_PASSWORD"] %>
  clickhouse:
    <<: *clickhouse
